### PR TITLE
Add the ability to add metrics based on certain scheduler events

### PR DESCRIPTION
**Pull request by thisiscab**
We're currently integration our solutions with DataDog. We wanted to
integrate that ability to send metrics to that service from our
Pipeline.

Doing such, will allow us to monitor the status of our Pipeline by
looking at statistics based on metrics sent by the pipeline.

At this moment, there is only one event that's supported but as the
feature progress forward, it's easy to see that we could support a bunch
more.

I had an implementation that was fairly basic at first but after
navigating on the existing PR against the official Luigi repo I've
discovered that there an ongoing implementation of exactly what we were
trying to achieve but with similar service. Thanks to chrispalmer, I've
been able to re-use his original work to implement ours.

https://github.com/spotify/luigi/pull/2044

### CODE REVIEW

**Review by tpalacio — COMMENTED** [review]
This is really cool. Glad you were able to leverage existing code. In addition to monitoring the progress of Luigi tasks it would be great to log the meta data of these tasks too (e.g. # rows loaded/deleted/modified, time duration, etc). Does it make sense for this type of data to live in Datadog or would you suggest it get stored somewhere else?

**Comment by thisiscab** [comment]
@tpalacio That's def. possible. This current implementation supports a generic behavior and I think it's out of scope for the moment. 

I'll add this to my to-do list as it's a good idea, but won't be part of this PR!

**Comment by thisiscab** [comment]
@tpalacio My main struggle is that I'm unable to add custom code that is specific to our implementation as an override in our project instead of polluting the luigi repo. 

I've been fighting really hard to try to find a way but I'm giving up. I can't find a solution to override the Luigi code directly in our project.

**Comment by tpalacio** [comment]
@cabouffard I'm not sure I understand. Are you saying that this entire PR is scrapped because it doesn't work with Luigi. Or are you saying that you are not going to try to support additional logging (e.g. # rows loaded/deleted/modified, time duration, etc) in this PR?

**Comment by thisiscab** [comment]
@tpalacio I'm saying neither. If you hadn't realized, we're on the glossier/luigi repo at the moment. I don't want our specific implementation to reside here, I would like it to reside in our data-warehouse code. Either way, I think I've been clear, you can DM me if you want more information!

**Comment by thisiscab** [comment]
You guys had your chances to review -- now merging this!

**Pull request merged**
